POLYNOMIAL a;
POLYNOMIAL b;
POLYNOMIAL aa(0, 1);
POLYNOMIAL bb(0, -1);
POLYNOMIAL c(1, 2, 10);
POLYNOMIAL d(0, 10);
POLYNOMIAL e(2, 500, 10, 50000);
POLYNOMIAL f;

cout << (a == a) << (a != a) << (a > a) << (a >= a) << (a < a) << (a <= a);
cout << (a == b) << (a != b) << (a > b) << (a >= b) << (a < b) << (a <= b);
cout << (a == aa) << (a != aa) << (a > aa) << (a >= aa) << (a < aa) << (a <= aa);
cout << (a == bb) << (a != bb) << (a > bb) << (a >= bb) << (a < bb) << (a <= bb);
cout << (a == c) << (a != c) << (a > c) << (a >= c) << (a < c) << (a <= c);
cout << (a == d) << (a != d) << (a > d) << (a >= d) << (a < d) << (a <= d);
cout << (a == e) << (a != e) << (a > e) << (a >= e) << (a < e) << (a <= e);
cout << (a == f) << (a != f) << (a > f) << (a >= f) << (a < f) << (a <= f);
cout << (b == a) << (b != a) << (b > a) << (b >= a) << (b < a) << (b <= a);
cout << (b == b) << (b != b) << (b > b) << (b >= b) << (b < b) << (b <= b);
cout << (b == aa) << (b != aa) << (b > aa) << (b >= aa) << (b < aa) << (b <= aa);
cout << (b == bb) << (b != bb) << (b > bb) << (b >= bb) << (b < bb) << (b <= bb);
cout << (b == c) << (b != c) << (b > c) << (b >= c) << (b < c) << (b <= c);
cout << (b == d) << (b != d) << (b > d) << (b >= d) << (b < d) << (b <= d);
cout << (b == e) << (b != e) << (b > e) << (b >= e) << (b < e) << (b <= e);
cout << (b == f) << (b != f) << (b > f) << (b >= f) << (b < f) << (b <= f);
cout << (aa == a) << (aa != a) << (aa > a) << (aa >= a) << (aa < a) << (aa <= a);
cout << (aa == b) << (aa != b) << (aa > b) << (aa >= b) << (aa < b) << (aa <= b);
cout << (aa == aa) << (aa != aa) << (aa > aa) << (aa >= aa) << (aa < aa) << (aa <= aa);
cout << (aa == bb) << (aa != bb) << (aa > bb) << (aa >= bb) << (aa < bb) << (aa <= bb);
cout << (aa == c) << (aa != c) << (aa > c) << (aa >= c) << (aa < c) << (aa <= c);
cout << (aa == d) << (aa != d) << (aa > d) << (aa >= d) << (aa < d) << (aa <= d);
cout << (aa == e) << (aa != e) << (aa > e) << (aa >= e) << (aa < e) << (aa <= e);
cout << (aa == f) << (aa != f) << (aa > f) << (aa >= f) << (aa < f) << (aa <= f);
cout << (bb == a) << (bb != a) << (bb > a) << (bb >= a) << (bb < a) << (bb <= a);
cout << (bb == b) << (bb != b) << (bb > b) << (bb >= b) << (bb < b) << (bb <= b);
cout << (bb == aa) << (bb != aa) << (bb > aa) << (bb >= aa) << (bb < aa) << (bb <= aa);
cout << (bb == bb) << (bb != bb) << (bb > bb) << (bb >= bb) << (bb < bb) << (bb <= bb);
cout << (bb == c) << (bb != c) << (bb > c) << (bb >= c) << (bb < c) << (bb <= c);
cout << (bb == d) << (bb != d) << (bb > d) << (bb >= d) << (bb < d) << (bb <= d);
cout << (bb == e) << (bb != e) << (bb > e) << (bb >= e) << (bb < e) << (bb <= e);
cout << (bb == f) << (bb != f) << (bb > f) << (bb >= f) << (bb < f) << (bb <= f);
cout << (c == a) << (c != a) << (c > a) << (c >= a) << (c < a) << (c <= a);
cout << (c == b) << (c != b) << (c > b) << (c >= b) << (c < b) << (c <= b);
cout << (c == aa) << (c != aa) << (c > aa) << (c >= aa) << (c < aa) << (c <= aa);
cout << (c == bb) << (c != bb) << (c > bb) << (c >= bb) << (c < bb) << (c <= bb);
cout << (c == c) << (c != c) << (c > c) << (c >= c) << (c < c) << (c <= c);
cout << (c == d) << (c != d) << (c > d) << (c >= d) << (c < d) << (c <= d);
cout << (c == e) << (c != e) << (c > e) << (c >= e) << (c < e) << (c <= e);
cout << (c == f) << (c != f) << (c > f) << (c >= f) << (c < f) << (c <= f);
cout << (d == a) << (d != a) << (d > a) << (d >= a) << (d < a) << (d <= a);
cout << (d == b) << (d != b) << (d > b) << (d >= b) << (d < b) << (d <= b);
cout << (d == aa) << (d != aa) << (d > aa) << (d >= aa) << (d < aa) << (d <= aa);
cout << (d == bb) << (d != bb) << (d > bb) << (d >= bb) << (d < bb) << (d <= bb);
cout << (d == c) << (d != c) << (d > c) << (d >= c) << (d < c) << (d <= c);
cout << (d == d) << (d != d) << (d > d) << (d >= d) << (d < d) << (d <= d);
cout << (d == e) << (d != e) << (d > e) << (d >= e) << (d < e) << (d <= e);
cout << (d == f) << (d != f) << (d > f) << (d >= f) << (d < f) << (d <= f);
cout << (e == a) << (e != a) << (e > a) << (e >= a) << (e < a) << (e <= a);
cout << (e == b) << (e != b) << (e > b) << (e >= b) << (e < b) << (e <= b);
cout << (e == aa) << (e != aa) << (e > aa) << (e >= aa) << (e < aa) << (e <= aa);
cout << (e == bb) << (e != bb) << (e > bb) << (e >= bb) << (e < bb) << (e <= bb);
cout << (e == c) << (e != c) << (e > c) << (e >= c) << (e < c) << (e <= c);
cout << (e == d) << (e != d) << (e > d) << (e >= d) << (e < d) << (e <= d);
cout << (e == e) << (e != e) << (e > e) << (e >= e) << (e < e) << (e <= e);
cout << (e == f) << (e != f) << (e > f) << (e >= f) << (e < f) << (e <= f);
cout << (f == a) << (f != a) << (f > a) << (f >= a) << (f < a) << (f <= a);
cout << (f == b) << (f != b) << (f > b) << (f >= b) << (f < b) << (f <= b);
cout << (f == aa) << (f != aa) << (f > aa) << (f >= aa) << (f < aa) << (f <= aa);
cout << (f == bb) << (f != bb) << (f > bb) << (f >= bb) << (f < bb) << (f <= bb);
cout << (f == c) << (f != c) << (f > c) << (f >= c) << (f < c) << (f <= c);
cout << (f == d) << (f != d) << (f > d) << (f >= d) << (f < d) << (f <= d);
cout << (f == e) << (f != e) << (f > e) << (f >= e) << (f < e) << (f <= e);
cout << (f == f) << (f != f) << (f > f) << (f >= f) << (f < f) << (f <= f);
cout << a << a << (a+a) << (a+a) << (a-a) << (a-a) << (a*a) << (a*a) << (a/a) << (a/a) << (a%a) << (a%a) << -a << -a << '\n';
cout << a << b << (a+b) << (b+a) << (a-b) << (b-a) << (a*b) << (b*a) << (a/b) << (b/a) << (a%b) << (b%a) << -a << -b << '\n';
cout << a << aa << (a+aa) << (aa+a) << (a-aa) << (aa-a) << (a*aa) << (aa*a) << (a/aa) << (aa/a) << (a%aa) << (aa%a) << -a << -aa << '\n';
cout << a << bb << (a+bb) << (bb+a) << (a-bb) << (bb-a) << (a*bb) << (bb*a) << (a/bb) << (bb/a) << (a%bb) << (bb%a) << -a << -bb << '\n';
cout << a << c << (a+c) << (c+a) << (a-c) << (c-a) << (a*c) << (c*a) << (a/c) << (c/a) << (a%c) << (c%a) << -a << -c << '\n';
cout << a << d << (a+d) << (d+a) << (a-d) << (d-a) << (a*d) << (d*a) << (a/d) << (d/a) << (a%d) << (d%a) << -a << -d << '\n';
cout << a << e << (a+e) << (e+a) << (a-e) << (e-a) << (a*e) << (e*a) << (a/e) << (e/a) << (a%e) << (e%a) << -a << -e << '\n';
cout << a << f << (a+f) << (f+a) << (a-f) << (f-a) << (a*f) << (f*a) << (a/f) << (f/a) << (a%f) << (f%a) << -a << -f << '\n';
cout << b << a << (b+a) << (a+b) << (b-a) << (a-b) << (b*a) << (a*b) << (b/a) << (a/b) << (b%a) << (a%b) << -b << -a << '\n';
cout << b << b << (b+b) << (b+b) << (b-b) << (b-b) << (b*b) << (b*b) << (b/b) << (b/b) << (b%b) << (b%b) << -b << -b << '\n';
cout << b << aa << (b+aa) << (aa+b) << (b-aa) << (aa-b) << (b*aa) << (aa*b) << (b/aa) << (aa/b) << (b%aa) << (aa%b) << -b << -aa << '\n';
cout << b << bb << (b+bb) << (bb+b) << (b-bb) << (bb-b) << (b*bb) << (bb*b) << (b/bb) << (bb/b) << (b%bb) << (bb%b) << -b << -bb << '\n';
cout << b << c << (b+c) << (c+b) << (b-c) << (c-b) << (b*c) << (c*b) << (b/c) << (c/b) << (b%c) << (c%b) << -b << -c << '\n';
cout << b << d << (b+d) << (d+b) << (b-d) << (d-b) << (b*d) << (d*b) << (b/d) << (d/b) << (b%d) << (d%b) << -b << -d << '\n';
cout << b << e << (b+e) << (e+b) << (b-e) << (e-b) << (b*e) << (e*b) << (b/e) << (e/b) << (b%e) << (e%b) << -b << -e << '\n';
cout << b << f << (b+f) << (f+b) << (b-f) << (f-b) << (b*f) << (f*b) << (b/f) << (f/b) << (b%f) << (f%b) << -b << -f << '\n';
cout << aa << a << (aa+a) << (a+aa) << (aa-a) << (a-aa) << (aa*a) << (a*aa) << (aa/a) << (a/aa) << (aa%a) << (a%aa) << -aa << -a << '\n';
cout << aa << b << (aa+b) << (b+aa) << (aa-b) << (b-aa) << (aa*b) << (b*aa) << (aa/b) << (b/aa) << (aa%b) << (b%aa) << -aa << -b << '\n';
cout << aa << aa << (aa+aa) << (aa+aa) << (aa-aa) << (aa-aa) << (aa*aa) << (aa*aa) << (aa/aa) << (aa/aa) << (aa%aa) << (aa%aa) << -aa << -aa << '\n';
cout << aa << bb << (aa+bb) << (bb+aa) << (aa-bb) << (bb-aa) << (aa*bb) << (bb*aa) << (aa/bb) << (bb/aa) << (aa%bb) << (bb%aa) << -aa << -bb << '\n';
cout << aa << c << (aa+c) << (c+aa) << (aa-c) << (c-aa) << (aa*c) << (c*aa) << (aa/c) << (c/aa) << (aa%c) << (c%aa) << -aa << -c << '\n';
cout << aa << d << (aa+d) << (d+aa) << (aa-d) << (d-aa) << (aa*d) << (d*aa) << (aa/d) << (d/aa) << (aa%d) << (d%aa) << -aa << -d << '\n';
cout << aa << e << (aa+e) << (e+aa) << (aa-e) << (e-aa) << (aa*e) << (e*aa) << (aa/e) << (e/aa) << (aa%e) << (e%aa) << -aa << -e << '\n';
cout << aa << f << (aa+f) << (f+aa) << (aa-f) << (f-aa) << (aa*f) << (f*aa) << (aa/f) << (f/aa) << (aa%f) << (f%aa) << -aa << -f << '\n';
cout << bb << a << (bb+a) << (a+bb) << (bb-a) << (a-bb) << (bb*a) << (a*bb) << (bb/a) << (a/bb) << (bb%a) << (a%bb) << -bb << -a << '\n';
cout << bb << b << (bb+b) << (b+bb) << (bb-b) << (b-bb) << (bb*b) << (b*bb) << (bb/b) << (b/bb) << (bb%b) << (b%bb) << -bb << -b << '\n';
cout << bb << aa << (bb+aa) << (aa+bb) << (bb-aa) << (aa-bb) << (bb*aa) << (aa*bb) << (bb/aa) << (aa/bb) << (bb%aa) << (aa%bb) << -bb << -aa << '\n';
cout << bb << bb << (bb+bb) << (bb+bb) << (bb-bb) << (bb-bb) << (bb*bb) << (bb*bb) << (bb/bb) << (bb/bb) << (bb%bb) << (bb%bb) << -bb << -bb << '\n';
cout << bb << c << (bb+c) << (c+bb) << (bb-c) << (c-bb) << (bb*c) << (c*bb) << (bb/c) << (c/bb) << (bb%c) << (c%bb) << -bb << -c << '\n';
cout << bb << d << (bb+d) << (d+bb) << (bb-d) << (d-bb) << (bb*d) << (d*bb) << (bb/d) << (d/bb) << (bb%d) << (d%bb) << -bb << -d << '\n';
cout << bb << e << (bb+e) << (e+bb) << (bb-e) << (e-bb) << (bb*e) << (e*bb) << (bb/e) << (e/bb) << (bb%e) << (e%bb) << -bb << -e << '\n';
cout << bb << f << (bb+f) << (f+bb) << (bb-f) << (f-bb) << (bb*f) << (f*bb) << (bb/f) << (f/bb) << (bb%f) << (f%bb) << -bb << -f << '\n';
cout << c << a << (c+a) << (a+c) << (c-a) << (a-c) << (c*a) << (a*c) << (c/a) << (a/c) << (c%a) << (a%c) << -c << -a << '\n';
cout << c << b << (c+b) << (b+c) << (c-b) << (b-c) << (c*b) << (b*c) << (c/b) << (b/c) << (c%b) << (b%c) << -c << -b << '\n';
cout << c << aa << (c+aa) << (aa+c) << (c-aa) << (aa-c) << (c*aa) << (aa*c) << (c/aa) << (aa/c) << (c%aa) << (aa%c) << -c << -aa << '\n';
cout << c << bb << (c+bb) << (bb+c) << (c-bb) << (bb-c) << (c*bb) << (bb*c) << (c/bb) << (bb/c) << (c%bb) << (bb%c) << -c << -bb << '\n';
cout << c << c << (c+c) << (c+c) << (c-c) << (c-c) << (c*c) << (c*c) << (c/c) << (c/c) << (c%c) << (c%c) << -c << -c << '\n';
cout << c << d << (c+d) << (d+c) << (c-d) << (d-c) << (c*d) << (d*c) << (c/d) << (d/c) << (c%d) << (d%c) << -c << -d << '\n';
cout << c << e << (c+e) << (e+c) << (c-e) << (e-c) << (c*e) << (e*c) << (c/e) << (e/c) << (c%e) << (e%c) << -c << -e << '\n';
cout << c << f << (c+f) << (f+c) << (c-f) << (f-c) << (c*f) << (f*c) << (c/f) << (f/c) << (c%f) << (f%c) << -c << -f << '\n';
cout << d << a << (d+a) << (a+d) << (d-a) << (a-d) << (d*a) << (a*d) << (d/a) << (a/d) << (d%a) << (a%d) << -d << -a << '\n';
cout << d << b << (d+b) << (b+d) << (d-b) << (b-d) << (d*b) << (b*d) << (d/b) << (b/d) << (d%b) << (b%d) << -d << -b << '\n';
cout << d << aa << (d+aa) << (aa+d) << (d-aa) << (aa-d) << (d*aa) << (aa*d) << (d/aa) << (aa/d) << (d%aa) << (aa%d) << -d << -aa << '\n';
cout << d << bb << (d+bb) << (bb+d) << (d-bb) << (bb-d) << (d*bb) << (bb*d) << (d/bb) << (bb/d) << (d%bb) << (bb%d) << -d << -bb << '\n';
cout << d << c << (d+c) << (c+d) << (d-c) << (c-d) << (d*c) << (c*d) << (d/c) << (c/d) << (d%c) << (c%d) << -d << -c << '\n';
cout << d << d << (d+d) << (d+d) << (d-d) << (d-d) << (d*d) << (d*d) << (d/d) << (d/d) << (d%d) << (d%d) << -d << -d << '\n';
cout << d << e << (d+e) << (e+d) << (d-e) << (e-d) << (d*e) << (e*d) << (d/e) << (e/d) << (d%e) << (e%d) << -d << -e << '\n';
cout << d << f << (d+f) << (f+d) << (d-f) << (f-d) << (d*f) << (f*d) << (d/f) << (f/d) << (d%f) << (f%d) << -d << -f << '\n';
cout << e << a << (e+a) << (a+e) << (e-a) << (a-e) << (e*a) << (a*e) << (e/a) << (a/e) << (e%a) << (a%e) << -e << -a << '\n';
cout << e << b << (e+b) << (b+e) << (e-b) << (b-e) << (e*b) << (b*e) << (e/b) << (b/e) << (e%b) << (b%e) << -e << -b << '\n';
cout << e << aa << (e+aa) << (aa+e) << (e-aa) << (aa-e) << (e*aa) << (aa*e) << (e/aa) << (aa/e) << (e%aa) << (aa%e) << -e << -aa << '\n';
cout << e << bb << (e+bb) << (bb+e) << (e-bb) << (bb-e) << (e*bb) << (bb*e) << (e/bb) << (bb/e) << (e%bb) << (bb%e) << -e << -bb << '\n';
cout << e << c << (e+c) << (c+e) << (e-c) << (c-e) << (e*c) << (c*e) << (e/c) << (c/e) << (e%c) << (c%e) << -e << -c << '\n';
cout << e << d << (e+d) << (d+e) << (e-d) << (d-e) << (e*d) << (d*e) << (e/d) << (d/e) << (e%d) << (d%e) << -e << -d << '\n';
cout << e << e << (e+e) << (e+e) << (e-e) << (e-e) << (e*e) << (e*e) << (e/e) << (e/e) << (e%e) << (e%e) << -e << -e << '\n';
cout << e << f << (e+f) << (f+e) << (e-f) << (f-e) << (e*f) << (f*e) << (e/f) << (f/e) << (e%f) << (f%e) << -e << -f << '\n';
cout << f << a << (f+a) << (a+f) << (f-a) << (a-f) << (f*a) << (a*f) << (f/a) << (a/f) << (f%a) << (a%f) << -f << -a << '\n';
cout << f << b << (f+b) << (b+f) << (f-b) << (b-f) << (f*b) << (b*f) << (f/b) << (b/f) << (f%b) << (b%f) << -f << -b << '\n';
cout << f << aa << (f+aa) << (aa+f) << (f-aa) << (aa-f) << (f*aa) << (aa*f) << (f/aa) << (aa/f) << (f%aa) << (aa%f) << -f << -aa << '\n';
cout << f << bb << (f+bb) << (bb+f) << (f-bb) << (bb-f) << (f*bb) << (bb*f) << (f/bb) << (bb/f) << (f%bb) << (bb%f) << -f << -bb << '\n';
cout << f << c << (f+c) << (c+f) << (f-c) << (c-f) << (f*c) << (c*f) << (f/c) << (c/f) << (f%c) << (c%f) << -f << -c << '\n';
cout << f << d << (f+d) << (d+f) << (f-d) << (d-f) << (f*d) << (d*f) << (f/d) << (d/f) << (f%d) << (d%f) << -f << -d << '\n';
cout << f << e << (f+e) << (e+f) << (f-e) << (e-f) << (f*e) << (e*f) << (f/e) << (e/f) << (f%e) << (e%f) << -f << -e << '\n';
cout << f << f << (f+f) << (f+f) << (f-f) << (f-f) << (f*f) << (f*f) << (f/f) << (f/f) << (f%f) << (f%f) << -f << -f << '\n';

cout << POLYNOMIAL::overloaded << endl;
POLYNOMIAL* twojstary = new POLYNOMIAL;
cout << POLYNOMIAL::overloaded << endl;
POLYNOMIAL* twojastara = new POLYNOMIAL(4, 1, 2, 3, 4, 5);
cout << POLYNOMIAL::overloaded << endl;
cout << *twojstary << " " << *twojastara << endl;
delete twojstary;
cout << POLYNOMIAL::overloaded << endl;
delete twojastara;
cout << POLYNOMIAL::overloaded << endl;
